services:
  vite:
    image: ghcr.io/melandry27/cube1groupecda/back-office:main
    restart: unless-stopped
    ports:
      - "80:3002"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
