services:
  express:
    image: ghcr.io/melandry27/cube1groupecda/api:main
    restart: unless-stopped
    environment:
      - NODE_ENV=prod
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
